"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });
import Footer from "@/components/footer/Footer";
import useTheme from "./hooks/useTheme";
import DarkMode from "@/components/navbar/DarkMode";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [darkMode, toggleDarkMode] = useTheme();
  return (
    <html lang="en " className={darkMode}>
      <body
        className="flex flex-col justify-between
      dark:bg-black dark:text-white transition-colors duration-500 
      "
      >
        <header>
          <Navbar>
            <DarkMode darkMode={darkMode} toggleDarkMode={toggleDarkMode} />
          </Navbar>
        </header>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
